apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: safebucket-secrets
  namespace: safebucket
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: safebucket-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:

  #APP__ADMIN_PASSWORD: "" # initial admin account password
  #APP__MFA_ENCRYPTION_KEY: "" # EXACTLY 32 characters (AES-256)
  - secretKey: APP__TOKEN_SECRET
    remoteRef:
      key: "safebucket-secrets/token_secret"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: APP__ADMIN_PASSWORD
    remoteRef:
      key: "safebucket-secrets/password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: APP__MFA_ENCRYPTION_KEY
    remoteRef:
      key: "safebucket-secrets/encryption_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
