{{- if .Values.palworld.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: palworld
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: palworld
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  sources:
    - path: charts/palworld
      {{- include "infra-repository-values" . | nindent 6 }}
      helm:
        values: |
          service:
            annotations:
              metallb.io/loadBalancerIPs: 192.168.1.185

          image:
            tag: 47248a2

          persistence:
            storageClass: nfs-k8s

          resources:
            limits:
              cpu: 4000m
              memory: 12Gi
            requests:
              cpu: 2000m
              memory: 8Gi

          panel:
            enabled: true
            expose: true
            hostname: {{ .Values.palworld.hostname }}

          config:
            env:
              TZ: Europe/Amsterdam
              COMMUNITY_SERVER: true
              SERVER_NAME: {{ .Values.palworld.name }}
              SERVER_DESCRIPTION: {{ .Values.palworld.description }}
              PUBLIC_IP: {{ .Values.palworld.publicIP | quote }}

              BACKUP_RETENTION_AMOUNT_TO_KEEP: 4

              DIFFICULTY: Normal
              EXP_RATE: 1.25
              PAL_SPAWN_NUM_RATE: 1.1
              PLAYER_STOMACH_DECREASE_RATE: 0.9
              PLAYER_STAMINA_DECREACE_RATE: 0.9
              PLAYER_AUTO_HP_REGENE_RATE: 1.2
              ENEMY_DROP_ITEM_RATE: 1.2
              WORK_SPEED_RATE: 1.2

              {{- if .Values.palworld.discordWebHook }}
              DISCORD_STATUS_ENABLED:  true
              DISCORD_STATUS_WEBHOOK_URL: {{ .Values.palworld.discordWebHook }}
              {{- end }}
{{- end }}
