apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-media-pv
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5T
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/zero-two/media"
    server: {{ .Values.nfs.server }}
    readOnly: false
