apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: tailscale-auth
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: TS_AUTHKEY 
    remoteRef:
      key: "tailscale/auth_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
