apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
spec:
  refreshInterval: "24h0m0s"
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: github-webhook
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
    - secretKey: "token"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "webhook-secret/webhook.github.secret"
        metadataPolicy: None
