apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-tracker-secret
spec:
  refreshInterval: "24h0m0s"
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: speedtest-tracker-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
    - secretKey: "APP_KEY"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "speedtest-tracker/APP_KEY"
        metadataPolicy: None
