apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reddit-autoposter-{{ .Values.name }}-config
  namespace: reddit-autoposter
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.name }}
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: "reddit-autoposter/reddit/client_id"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: clientSecret
    remoteRef:
      key: "reddit-autoposter/reddit/client_secret"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: username
    remoteRef:
      key: "reddit-autoposter/reddit/username"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: password
    remoteRef:
      key: "reddit-autoposter/reddit/password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: config.toml
    remoteRef:
      key: "reddit-autoposter/{{ .Values.name }}/config"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
