apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: calibre-web-automated
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  name: calibre-web-automated
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre-web-automated 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre-web-automated
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Amsterdam
          image: crocodilestick/calibre-web-automated:v4.0.6
          imagePullPolicy: Always #Always enables updates with a rollout restart
          name: calibre-web-automated
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: calibre-web-automated-config
            - mountPath: /calibre-library
              name: calibre-library
            - mountPath: /cwa-book-ingest
              name: calibre-web-automated-ingest
              subPath: books
          resources: {} # Add resource requests/limits here if needed
      restartPolicy: Always
      # Volumes will vary based on your storage solution - here Longhorn PVCs are used
      # except for the ingest folder which is a hostPath to a NAS mount so files can be 
      # manually deposited for import (or via automation)
      volumes:
        - name: calibre-web-automated-config
          persistentVolumeClaim:
            claimName: calibre-web-automated-config
        - name: calibre-library
          persistentVolumeClaim:
            claimName: calibre-web-automated-library
        - name: calibre-web-automated-ingest
          persistentVolumeClaim:
            claimName: servarr-media-pvc
