apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-automated-library
spec:
  storageClassName: 'nfs-k8s'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
