apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: servarr
    name: in-cluster
  project: servarr
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  sources:
    - chart: servarr
      repoURL: https://charts.kubito.dev/kubitodev/servarr
      targetRevision: 1.5.2
