apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hachimitsu-secrets
  namespace: yugen
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: hachimitsu-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: WEBHOOK_AUTHORIZATION_TOKEN
    remoteRef:
      key: "yugen-secrets/shared/WEBHOOK_AUTHORIZATION_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: "yugen-secrets/hachimitsu/DISCORD_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: TOP_GG_TOKEN
    remoteRef:
      key: "yugen-secrets/hachimitsu/TOP_GG_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: DISCORDBOTLIST_TOKEN
    remoteRef:
      key: "yugen-secrets/hachimitsu/DISCORDBOTLIST_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: SENTRY_DSN
    remoteRef:
      key: "yugen-secrets/hachimitsu/SENTRY_DSN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
