apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoshi-secrets
  namespace: yugen
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: hoshi-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: "yugen-bots/hoshi/DISCORD_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
