apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kusari-secrets
  namespace: yugen
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: kusari-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: WEBHOOK_AUTHORIZATION_TOKEN
    remoteRef:
      key: "yugen-bots/shared/WEBHOOK_AUTHORIZATION_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: "yugen-bots/kusari/DISCORD_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: TOP_GG_TOKEN
    remoteRef:
      key: "yugen-bots/kusari/TOP_GG_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: DISCORDBOTLIST_TOKEN
    remoteRef:
      key: "yugen-bots/kusari/DISCORDBOTLIST_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: SENTRY_DSN
    remoteRef:
      key: "yugen-bots/kusari/SENTRY_DSN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: WIKTIONARY_USERNAME
    remoteRef:
      key: "yugen-bots/kusari/WIKTIONARY_USERNAME"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: WIKTIONARY_PASSWORD
    remoteRef:
      key: "yugen-bots/kusari/WIKTIONARY_PASSWORD"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
