apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sairo-secrets
  namespace: sairo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: sairo-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:

  #APP__ADMIN_PASSWORD: "" # initial admin account password
  #APP__MFA_ENCRYPTION_KEY: "" # EXACTLY 32 characters (AES-256)
  - secretKey: s3-access-key
    remoteRef:
      key: "sairo-secrets/access_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: s3-secret-key
    remoteRef:
      key: "sairo-secrets/secret_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: admin-password
    remoteRef:
      key: "sairo-secrets/password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: jwt-secret
    remoteRef:
      key: "sairo-secrets/jwt_secret"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
