apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cvc-secrets
  namespace: clan-europe-legacy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: cvc-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: TOKEN
    remoteRef:
      key: "clan-europe-legacy-secrets/cvc/discord_token"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: SUPABASE_KEY
    remoteRef:
      key: "clan-europe-legacy-secrets/cvc/supabase_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: service_account.json
    remoteRef:
      key: "clan-europe-legacy-secrets/cvc/service_account"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: config.json
    remoteRef:
      key: "clan-europe-legacy-secrets/cvc/config"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
