apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: muse-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "muse"
      images:
        - alias: "muse"
          imageName: "ghcr.io/elysium-stack/muse:main"
          commonUpdateSettings:
            updateStrategy: "digest"
