apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: muse-secrets
  namespace: muse 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: muse-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: "muse-secrets/DISCORD_TOKEN"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: DISCORD_OAUTH_CLIENT_SECRET
    remoteRef:
      key: "muse-secrets/DISCORD_OAUTH_CLIENT_SECRET"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
