argo-cd:
  configs:
    cm:
      exec.enabled: "true"
    params:
      application.namespaces: "argocd, zero-two, zero-two-*"
      server.insecure: "true"
      applicationsetcontroller.enable.policy.override: "true"
      controller.sync.timeout.seconds: "1800" # 30 mins
