apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destinations:
    - namespace: "homepage"
      name: in-cluster
    - namespace: "argocd"
      name: in-cluster
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  sourceRepos:
    - http://jameswynn.github.io/helm-charts
    - {{ .Values.repoURL }}
