apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: servarr
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  sources:
    - chart: servarr
      repoURL: https://charts.kubito.dev
      targetRevision: 1.5.2
      helm:
        releaseName: kubitodev
        values: |
          bazarr:
            enabled: false
          lidarr:
            enabled: false
          
          jellyfin:
            image:
              tag: 10.11.11
            env:
              TZ: "Europe/Amsterdam"
            enableDLNA: true
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - {{ .Values.servarr.jellyfin.hostname }}
            persistence:
              config:
                enabled: true
                storageClass: nfs-k8s
              media:
                enabled: false
              extraExistingClaimMounts:
                - name: media-nfs
                  existingClaim: servarr-media-pvc
                  mountPath: /mnt/media
                  readonly: false
            resources:
              limits:
                cpu: 6000m
                memory: 10Gi
              requests:
                cpu: 1000m
                memory: 2Gi

          sonarr:
            image:
              tag: 4.0.19
            env:
              TZ: "Europe/Amsterdam"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.sonarr.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s
              additionalVolumes:
                - name: media-nfs
                  persistentVolumeClaim:
                    claimName: servarr-media-pvc
              additionalMounts:
                - mountPath: /mnt/media
                  name: media-nfs

          radarr:
            image:
              tag: 6.3.0
            env:
              TZ: "Europe/Amsterdam"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.radarr.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s
              additionalVolumes:
                - name: media-nfs
                  persistentVolumeClaim:
                    claimName: servarr-media-pvc
              additionalMounts:
                - mountPath: /mnt/media
                  name: media-nfs

          prowlarr:
            image:
              tag: 2.5.1-develop
            env:
              TZ: "Europe/Amsterdam"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.prowlarr.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s

          flaresolverr:
            image:
              tag: v3.5.0
            env:
              TZ: "Europe/Amsterdam"

          qbittorrent:
            image:
              tag: 5.2.3
            env:
              TZ: "Europe/Amsterdam"
              DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.qbittorrent.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s
              additionalVolumes:
                - name: media-nfs
                  persistentVolumeClaim:
                    claimName: servarr-media-pvc
              additionalMounts:
                - mountPath: /mnt/media
                  name: media-nfs

          cleanuparr:
            enabled: false
            image:
              tag: 2.9.16
            env:
              TZ: "Europe/Amsterdam"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.cleanuparr.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s
              additionalVolumes:
                - name: media-nfs
                  persistentVolumeClaim:
                    claimName: servarr-media-pvc
              additionalMounts:
                - mountPath: /mnt/media
                  name: media-nfs

          seerr:
            image:
              tag: v3.3.0
            env:
              TZ: "Europe/Amsterdam"
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: traefik
              hosts:
                - host: {{ .Values.servarr.seerr.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            persistence:
              enabled: true
              storageClass: nfs-k8s
    - path: .
      repoURL: oci://oci.trueforge.org/truecharts/sabnzbd
      targetRevision: 25.3.0
      helm:
        values: |
          TZ: "Europe/Amsterdam"

          global:
            fallbackDefaults:
              storageClass: nfs-k8s

          ingress:
            main:
              enabled: true
              ingressClassName: traefik
              hosts:
                - host: {{ .Values.servarr.sabnzbd.hostname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              integrations:
                traefik:
                  enabled: true

          persistence:
            nfs-media:
              enabled: true
              type: pvc
              mountPath: /mnt/media
              targetSelectAll: true
              static:
                mode: nfs
                share: "/mnt/zero-two/media"
                server: {{ .Values.nfs.server | quote  }}

          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      SABNZBD__HOST_WHITELIST_ENTRIES: "{{ .Values.servarr.sabnzbd.hostname }},servarr-sabnzbd"
    - path: charts/calibre-web-automated
      {{- include "infra-repository-values" . | nindent 6 }}
      helm:
        values: |
          hostname: {{ .Values.servarr.calibreWeb.hostname }}
    - path: charts/resources/servarr
      {{- include "infra-repository-values" . | nindent 6 }}
      helm:
        values: |
          {{- .Values | toYaml | nindent 10 }}
