apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: servarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destinations:
    - namespace: "servarr"
      name: in-cluster
    - namespace: "argocd"
      name: in-cluster
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
  sourceRepos:
    - https://charts.kubito.dev
    - {{ .Values.repoURL }}
