{{- if .Values.speedtestTracker.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-tracker
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: speedtest-tracker
    name: in-cluster
  project: applications
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  sources:
    - chart: speedtest-tracker
      repoURL: oci://ghcr.io/harish2k01/helm-charts/speedtest-tracker
      targetRevision: v0.1.3
{{ end }}
