{{- if .Values.speedtestTracker.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: string-secret
  namespace: speedtest-tracker
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
{{- end }}
