{{- if .Values.speedtestTracker.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-secret
  namespace: speedtest-tracker
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: APP_KEY
{{- end }}
