{{- if .Values.yugen.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugen
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: yugen
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  sources:
    - chart: yugen
      repoURL: https://charts.yugen.bot
      targetRevision: 0.1.17
      helm:
        values: |
          global:
            config:
              OWNER_IDS: "256474214272335872"
              DISCORD_DEVELOPMENT_GUILD_ID: "1164669271310356507"
              DISCORD_LOGS_REPORT_CHANNEL_ID: "1165002458133708842"
              DISCORD_VOTE_REPORT_CHANNEL_ID:  "1165693413614682192"
            postgresql:
              auth:
                existingSecret: postgres-secrets
                secretKeys:
                adminPasswordKey: "postgres-password"
                userPasswordKey: "password"

          postgresql:
            auth:
              usePasswordFiles: false
              existingSecret: postgres-secrets
              secretKeys:
                adminPasswordKey: "postgres-password"
                userPasswordKey: "password"

          kusari:
            enabled: false
            secrets:
              existingSecret: kusari-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1186650405703262208"
              SHARD: "true"
              INVITE_LINK: "https://invite-kusari.yugen.bot"
              TOP_GG_SYNC: "true"
              TOP_GG_VOTE_LINK: "https://top.gg/bot/1186650405703262208/vote"
              DISCORDBOTLIST_SYNC: "true"
              DISCORDBOTLIST_VOTE_LINK: "https://discordbotlist.com/bots/kusari/upvote"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.kusari }}
                  paths:
                    - path: /
                      pathType: Prefix

          koto:
            enabled: false
            secrets:
              existingSecret: koto-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1164654805730472018"
              SHARD: "true"
              INVITE_LINK: "https://invite-koto.yugen.bot"
              TOP_GG_SYNC: "true"
              TOP_GG_VOTE_LINK: "https://top.gg/bot/1164654805730472018/vote"
              DISCORDBOTLIST_SYNC: "true"
              DISCORDBOTLIST_VOTE_LINK: "https://discordbotlist.com/bots/koto/upvote"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.koto }}
                  paths:
                    - path: /
                      pathType: Prefix

          kazu:
            enabled: false
            secrets:
              existingSecret: kazu-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1260679337594589356"
              SHARD: "false"
              INVITE_LINK: "https://invite-kazu.yugen.bot"
              TOP_GG_SYNC: "true"
              TOP_GG_VOTE_LINK: "https://top.gg/bot/1260679337594589356/vote"
              DISCORDBOTLIST_SYNC: "true"
              DISCORDBOTLIST_VOTE_LINK: "https://discordbotlist.com/bots/kazu/upvote"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.kazu }}
                  paths:
                    - path: /
                      pathType: Prefix

          hoshi:
            enabled: false
            secrets:
              existingSecret: hoshi-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1208707348659445800"
              SHARD: "false"
              INVITE_LINK: "https://invite-hoshi.yugen.bot"
              TOP_GG_SYNC: "true"
              TOP_GG_VOTE_LINK: "https://top.gg/bot/1208707348659445800/vote"
              DISCORDBOTLIST_SYNC: "true"
              DISCORDBOTLIST_VOTE_LINK: "https://discordbotlist.com/bots/hoshi-8125/upvote"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.hoshi }}
                  paths:
                    - path: /
                      pathType: Prefix

          hachimitsu:
            enabled: false
            secrets:
              existingSecret: hachimitsu-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1523707144644464831"
              SHARD: "false"
              INVITE_LINK: "https://invite-hachimitsu.yugen.bot"
              TOP_GG_SYNC: "true"
              TOP_GG_VOTE_LINK: "https://top.gg/bot/1523707144644464831/vote"
              DISCORDBOTLIST_SYNC: "true"
              DISCORDBOTLIST_VOTE_LINK: "https://discordbotlist.com/bots/hachimitsu/upvote"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.hachimitsu }}
                  paths:
                    - path: /
                      pathType: Prefix

          iro:
            enabled: true
            secrets:
              existingSecret: iro-secrets
            config:
              SYNC_COMMANDS: "true"
              DISCORD_APP_ID: "1305247349702135908"
              SHARD: "false"
            ingress:
              enabled: true
              className: traefik
              hosts:
                - host: {{ .Values.yugen.hostnames.iro }}
                  paths:
                    - path: /
                      pathType: Prefix

    - path: charts/resources/yugen
      {{- include "infra-repository-values" . | nindent 6 }}
{{- end }}
