apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-secrets
  namespace: palworld
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: palworld-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
    - secretKey: SERVER_PASSWORD
      remoteRef:
        key: "palworld-secrets/server_password"
        conversionStrategy: Default
        metadataPolicy: None
        decodingStrategy: None
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: "palworld-secrets/admin_password"
        conversionStrategy: Default
        metadataPolicy: None
        decodingStrategy: None
