apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpu-device-plugin
  namespace: inteldeviceplugins-system
spec:
  image: intel/intel-gpu-plugin:0.36.0
  sharedDevNum: 2
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
