apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "prometheus-stack/grafana/username"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: password
    remoteRef:
      key: "prometheus-stack/grafana/password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
