apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: hachimitsu-scrape-config
  labels:
    release: prometheus
spec:
  metricsPath: /api/metrics
  scrapeInterval: 1m
  staticConfigs:
    - labels:
        job: hachimitsu
      targets:
        - hachimitsu-api.yugen.bot
