apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: koto-scrape-config
  labels:
    release: prometheus
spec:
  metricsPath: /api/metrics
  scrapeInterval: 1m
  staticConfigs:
    - labels:
        job: koto
      targets:
        - koto-api.yugen.bot
