apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kusari-scrape-config
  labels:
    release: prometheus
spec:
  metricsPath: /api/metrics
  scrapeInterval: 1m
  staticConfigs:
    - labels:
        job: kusari
      targets:
        - kusari-api.yugen.bot
