apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: event-secrets
  namespace: clan-europe 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: event-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: "clan-europe-secrets/event/discord_token"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: POCKETBASE_PASSWORD
    remoteRef:
      key: "clan-europe-secrets/shared/pocketbase_password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: R2_ACCESS_KEY_ID
    remoteRef:
      key: "clan-europe-secrets/shared/r2_access_key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: R2_ACCESS_KEY_SECRET
    remoteRef:
      key: "clan-europe-secrets/shared/r2_access_secret"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
