{{- if .Values.enabled.applications }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destinations:
    - namespace: "zero-two"
      name: in-cluster
    - namespace: "argocd"
      name: in-cluster
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  sourceRepos:
    - oci://ghcr.io/harish2k01/helm-charts/speedtest-tracker
    - {{ .Values.repoURL }}
{{- end -}}

