{{- .Values.applications.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zero-two
    name: in-cluster
  project: structure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - path: charts/applications  
      {{- include "infra-repository-values" . | nindent 6 }}
      helm:
        values: |
          {{ .Values.applications | toYaml | nindent 10 }}
{{- end }
