{{- if .Values.enabled.arrStack }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: arr-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destinations:
    - namespace: "zero-two"
      name: in-cluster
    - namespace: "argocd"
      name: in-cluster
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  sourceRepos:
    - {{ .Values.repoURL }}
{{- end -}}

