{{- if .Values.enabled.ebookStack }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebook-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zero-two
    name: in-cluster
  project: ebook-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - path: charts/ebook-stack
      {{- include "infra-repository-values" . | nindent 6 }}
{{- end }}
