{{- if .Values.enabled.servarr }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: servarr-stack
    name: in-cluster
  project: servarr-stack
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - path: charts/servarr-stack
      {{- include "infra-repository-values" . | nindent 6 }}
      helm:
        values: |
          {{- include "infra-repository-values" . | nindent 10 }}
{{- end }}
