{{- if .Values.enabled.servarr }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: servarr-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destinations:
    - namespace: "servarr-stack"
      name: in-cluster
    - namespace: "argocd"
      name: in-cluster
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  sourceRepos:
    - {{ .Values.repoURL }}
{{- end -}}

