apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-secrets
  namespace: glance 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: glance-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: homeassistant
    remoteRef:
      key: "glance-secrets/homeassistant/key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: proxmox-token-id 
    remoteRef:
      key: "glance-secrets/proxmox/token-id"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: proxmox-token-secret
    remoteRef:
      key: "glance-secrets/proxmox/token-secret"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: pihole-key
    remoteRef:
      key: "glance-secrets/pihole/key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: truenas-key
    remoteRef:
      key: "glance-secrets/truenas/key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: jellyfin-key
    remoteRef:
      key: "glance-secrets/media/jellyfin-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: sabnzbd-key
    remoteRef:
      key: "glance-secrets/media/sabnzbd-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: qbittorrent-username
    remoteRef:
      key: "glance-secrets/media/qbittorrent-username"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: qbittorrent-password
    remoteRef:
      key: "glance-secrets/media/qbittorrent-password"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: prowlarr-key
    remoteRef:
      key: "glance-secrets/media/prowlarr-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: sonarr-key
    remoteRef:
      key: "glance-secrets/media/sonarr-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: radarr-key
    remoteRef:
      key: "glance-secrets/media/radarr-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: seerr-key
    remoteRef:
      key: "glance-secrets/media/seerr-key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: speedtest-tracker-key
    remoteRef:
      key: "glance-secrets/speedtest-tracker/key"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None

