apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-client-cert
spec:
  issuerRef:
    name: traefik-tls-issuer
    kind: ClusterIssuer
  secretName: cloudflare-client-cert
  commonName: traefik.zero-two.xyz
  duration: 87600h0m0s
  privateKey:
    rotationPolicy: Never
    algorithm: ECDSA

