repoURL: ""
targetRevision: HEAD

nfs:
  server: ""

speedtestTracker:
  enabled: true
  hostname: speed.zero-two.xyz
  schedule: "0 */3 * * *"

homepage:
  hostname: homepage.zero-two.xyz

servarr:
  jellyfin:
    hostname: jelly.zero-two.xyz
  seerr:
    hostname: request.zero-two.xyz
  radarr:
    hostname: radarr.zero-two.xyz
  sonarr:
    hostname: sonarr.zero-two.xyz
  qbittorrent:
    hostname: torrent.zero-two.xyz
  prowlarr:
    hostname: prowlarr.zero-two.xyz
  cleanuparr:
    hostname: cleanup.zero-two.xyz
  sabnzbd:
    hostname: sabnzbd.zero-two.xyz
  calibreWeb:
    hostname: calibre.zero-two.xyz

prometheus:
  hostname: prometheus.zero-two.xyz
