repoURL: ""
targetRevision: HEAD

nfs:
  server: ""

speedtestTracker:
  enabled: true
  hostname: speed.zero-two.xyz
  schedule: "0 */3 * * *"

homepage:
  enabled: false
  hostname: homepage.zero-two.xyz

glance:
  enabled: true
  hostname: glance.zero-two.xyz

hoppscotch:
  enabled: false
  hostname: hopp.zero-two.xyz

servarr:
  jellyfin:
    hostname: jelly.zero-two.xyz
  seerr:
    hostname: request.zero-two.xyz
  radarr:
    hostname: radarr.zero-two.xyz
  sonarr:
    hostname: sonarr.zero-two.xyz
  qbittorrent:
    hostname: torrent.zero-two.xyz
  prowlarr:
    hostname: prowlarr.zero-two.xyz
  cleanuparr:
    hostname: cleanup.zero-two.xyz
  sabnzbd:
    hostname: sabnzbd.zero-two.xyz
  calibreWeb:
    hostname: calibre.zero-two.xyz
  fladder:
    hostname: fladder.zero-two.xyz

prometheus:
  grafana:
    hostname: grafana.zero-two.xyz

bambuddy:
  enabled: true
  hostname: bambuddy.zero-two.xyz

redditAutoposter:
  - name: elysium

yugen:
  enabled: true
  hostnames:
    kusari: kusari-api.yugen.bot
    koto: koto-api.yugen.bot
    kazu: kazu-api.yugen.bot
    hoshi: hoshi-api.yugen.bot
    hachimitsu: hachimitsu-api.yugen.bot
    iro: iro-api.yugen.bot

muse:
  enabled: true
  hostname: muse-api.the-river-styx.com

databasus:
  enabled: true
  hostnames:
    - databasus.zero-two.xyz
