apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-updater-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: image-updater-registry
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
    creationPolicy: Owner
  data:
  - secretKey: creds
    remoteRef:
      key: "github-registry/creds"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
  - secretKey: token
    remoteRef:
      key: "github-registry/token"
      conversionStrategy: Default
      metadataPolicy: None
      decodingStrategy: None
