{{- range $secretName, $secret := .Values.stores }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ $secret.storeName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
  	{{- if eq $secret.provider "OnePasswordSDK" }}
    onepasswordSDK:
      vault: {{ $secret.providerParameters.vault }}
      auth:
        serviceAccountSecretRef:
          name: {{ $secret.tokenName }}
          namespace: {{ $.Release.Namespace }}
          key: token
	{{- end }}
---
{{- end }}
